package com.samuel.treinaiappcompose.ui.navigation

enum class Screens {
  ONBOARDING_SCREEN,
  SIGNUP_SCREEN,
  SIGNIN_SCREEN,
  ROUTINE_SCREEN,
  PROGRESS_SCREEN,
  PROFILE_SCREEN,
  SETTING_SCREEN,
  WORKOUT_LIST_SCREEN,
  WORKOUT_SCREEN,
  EXERCISE_SCREEN
}